user_default_conf:
  avator: "http://shortvideo.com/default.jpg"
  sign: "刚来，请多关照～"

mysql:
  address: "localhost"
  port: "3306"
  user: "admin"
  pwd: "123123"
  db_name: "sv"
  max_open_conns: 1000
  max_idle_conns: 50