mysql:
  address: "localhost"
  port: "3306"
  user: "admin"
  pwd: "123123"
  db_name: "sv"
  max_open_conns: 1000
  max_idle_conns: 50

redis:
  address: "localhost"
  port: 6379
  password: ""
  db: 0

minio:
  endpoint: "9.135.140.32:9090"
  access_key_id: "minioadmin"
  secret_access_key: "minioadmin"

