mysql:
  address: "localhost"
  port: "3306"
  user: "admin"
  pwd: "123123"
  db_name: "sv"
  max_open_conns: 1000
  max_idle_conns: 50

redis:
  address: "0.0.0.0:6379"
  port: 6379
  password: ""
  db: 0

minio:
  endpoint: "127.0.0.1:9000"
  access_key_id: "minioadmin"
  secret_access_key: "minioadmin"

comm_config:
  url_prefix: "http://127.0.0.1:9000/svtest"
